name: webcam-timelapse-lan

services:
  timelapse:
    build: ..
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [cpu, nvenc, vaapi] for accelerated transcoding
    ports:
      - "8080:8080"
    volumes:
      - ../config.yaml:/app/config.yaml:ro
      - ../data:/data
      - ../fonts:/app/fonts:ro
    restart: unless-stopped
    environment:
      - CONFIG_PATH=/app/config.yaml
